<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit780d50550985433524f7c5bd721684c6
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DHTMLX\\Connector\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DHTMLX\\Connector\\' => 
        array (
            0 => 'C:\\Apache24\\htdocs\\connector-php\\codebase',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit780d50550985433524f7c5bd721684c6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit780d50550985433524f7c5bd721684c6::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
